###        мллллл   ?
###      Аллл?пл?лВ пппллллллл?    пппппллВлл?    мВлллп
###     Бллл?  Бллп        пплллл?          пллл  Бллл?
###    Вллл      ?        лл? пллл?          АллВлл?
###   Вллл        мллллл? лл?  пллл мллллллм  Бллллл
###   лллА     Аллллп  пл?лл?   лллВлл? Ал? лллВлл?
###   Бллл     лллл?   лл лл?  Аллллллллллл?лллБ Бллл
###    Аллл?мллпВллм мл?Вл?  лллБлллА     мллл?  Аллл?
###      пллллл?  плллВп  лл?Аллл? плллллллВл?      пВлл?
###                        мллллллБ
###          пппллВмммммлВлллВп?   
###
###

[Settings]
### 
### Name of the current player
###
Username=CODEX
###
### Origin Account ID
###
AccountId=666666666
###
### Language that will be used in the game
###
Language=zh_TW
###
### Set Origin connection to offline mode
###
Offline=true
###